// Generated by CoffeeScript 1.9.2
(function() {
  var _toggle, enable;

  if (typeof localStorage['enable'] === 'undefined') {
    localStorage['enable'] = true;
  }

  enable = JSON.parse(localStorage['enable']);

  _toggle = function(_enable) {
    if (_enable) {
      chrome.browserAction.setIcon({
        path: 'icons/48.png'
      });
      return chrome.browserAction.setTitle({
        title: 'Image Info - running'
      });
    } else {
      chrome.browserAction.setIcon({
        path: 'icons/48_disable.png'
      });
      return chrome.browserAction.setTitle({
        title: 'disabled (click to enable)'
      });
    }
  };

  _toggle(enable);

  chrome.browserAction.onClicked.addListener(function(tab) {
    enable = !enable;
    localStorage['enable'] = enable;
    chrome.tabs.sendMessage(tab.id, enable);
    return _toggle(enable);
  });

  chrome.runtime.onMessage.addListener(function(request, sender, sendMessage) {
    return sendMessage(enable);
  });

}).call(this);

//# sourceMappingURL=background.js.map
